### ISSUE TITLE
"loggly is a legacy winston transport. Consider upgrading:"

### ISSUE THREAD

**Issue by weyert** [loggly/winston-loggly-bulk#45]
When I am using `winston-loggly-bulk` as defined in the `package.json` as:
```
    "winston-loggly-bulk": "https://github.com/loggly/winston-loggly-bulk.git#3.x",
```

I am getting the warning message:

```
loggly is a legacy winston transport. Consider upgrading:
- Upgrade docs: https://github.com/winstonjs/winston/blob/master/UPGRADE-3.0.md
```

**Comment by Shwetajain148** [comment]
Hi @weyert, thanks for reporting this.

I want to let you know that this is a known issue and currently being worked on. The `winston-loggly-bulk` library is using some legacy syntax of `winston` which have been removed in latest `winston's 3.x` release. Due to the legacy syntax, this message is displayed to users. 

The library is being upgraded to winston 3.x compatibility and should complete soon. We are also dependent on some other modules. 

Thanks for your patience.

**Comment by Shwetajain148** [comment]
Closing this issue since the same main thread is at- #32. Please follow the existing issue for further updates. 

Thanks!
